### ISSUE TITLE
CRD defaults are not actually applied

### ISSUE THREAD

**Issue by ericbottard** [projectriff/system#102]
Take `Stream.Spec.contentType` as an example: even though there is a call to [SetDefault](https://github.com/projectriff/system/blob/master/pkg/controllers/streaming/stream_controller.go#L84), the only thing that is ever updated is the Status subresource.

We need to revisit this pattern, which I assume we applied over the whole codebase.

**Comment by scothis** [comment]
We don't have the webhooks enabled right now. If you want the objects to contain defaults, after you load it, create a deep copy and then call SetDefaults locally. This would be the recommended course of action even if the Webhooks were enabled, since it's possible the resource was persisted without passing through the webhook, or the defaulting changed since the resource was persisted.

**Comment by ericbottard** [comment]
But shouldn't we then persist those (new) defaults?
Otherwise, we'd be acting on a view of the world (and computing a Status that we persist) which can't be explained by looking at the persisted Spec, which is surprising for users, isn't it?

**Comment by scothis** [comment]
The controller should not persist spec mutations on the resource it is reconciling. That behavior should be managed by a webhook.

I'm not suggesting the the current behavior is correct. I haven't gotten around to implementing the webhooks yet. But, the current behavior is also not wrong.

**Comment by ericbottard** [comment]
I also think the controller persisting things is weird/wrong. But then what that seems to mean is that it should not `SetDefaults`, even for an in-memory view only. As a matter of fact, once an API version is stabilized, defaults should not change. And thus, once the webhook has set defaults (and persisted them), the Spec should reflect the effective values, shouldn't it? Hence the reconciler shouldn't need to call that method

Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#defaulting

**Comment by scothis** [comment]
>  But then what that seems to mean is that it should not SetDefaults, even for an in-memory view only.

Applying the defaults in the controller is a safeguard. The resource could have been persisted previously, or the resource could have been created when the webhook was not in place. 99.99% of the time it's a no-op, but that 0.01% of the time it can protect against a panic.

> the Spec should reflect the effective values, shouldn't it?

It's the Spec's role to reflect the desired state, and the Status' role to reflect the current state. As long as the default is defined and applied consistently, it shouldn't matter whether the value is persisted or not.

**Comment by scothis** [comment]
Before we can enable the webhooks. We'll need cert-manager to be installed in the cluster.

**Comment by ericbottard** [comment]
Implemented in https://github.com/projectriff/system/commit/1662974f306b0fa7a586aa8f3fd41c69f1768683
