### ISSUE TITLE
Autoscaling support in the core runtime

### ISSUE THREAD

**Issue by scothis** [projectriff/system#143]
One of the key main benefits of the Knative runtime over the Core runtime is that it provides http based autoscaling for workloads. We should fill that gap.

Design principals:
- only use built-in (core) kubernetes types, like HorizontalPodAutoscaler
- utilize the scale subresoruce on Deployer
- provide an opinionated metric for scaling, allowing the user to define the boundaries or tune as needed

Other things to keep in mind:
- it's ok for zero-to-one autoscaling to be out of scope
- invokers may need to take more responsibility to finish current work before terminating

**Comment by dprotaso** [comment]
For reference (how to configure HPA to scale on custom metrics) see issue and related PR:
https://github.com/knative/serving/issues/3134

**Comment by dprotaso** [comment]
After some slack discussion:

The intent of the issue is to wire up the Horizontal Pod Autoscaler and to scale on the built in metrics (cpu & memory).
