### ISSUE TITLE
Make the service name used by a core deployer configurable

### ISSUE THREAD

**Issue by trisberg** [projectriff/system#200]
Currently the deployers generate a service name to keep them unique. This makes it harder to discover services since you can't bind using just the DNS name, you would have to look it up based on labels. We should provide a way to define the actual name used and the end-user would be responsible for avoiding clashes. If user doesn't specify the name, then we should generate one as we do today.

**Comment by jldec** [comment]
Good idea, i like it. Was there a reason not to use the deployer name as the default service name?

**Comment by jldec** [comment]
Example with proposed CLI flag
`riff core deployer create inventory --expose-service-as mysvc`

If flag is not provided, the current (auto-generated) name is used.
Defaulting to match the deployer name can result in conflicts so avoiding that for now.

**Comment by glyn** [comment]
@scothis is questioning this approach - re-opening for further discussion.

**Comment by glyn** [comment]
The guidance that is being developed in [RFC 0006](https://github.com/projectriff/riff/pull/1369) suggests that we generate a static name (maybe even without suffix) as user-specified names for auto-generated resources create a number of edge cases.

So let's revert the earlier implementation of this issue and follow up with another issue.
