### ISSUE TITLE
Status conditions are shared between custom resources

### ISSUE THREAD

**Issue by glyn** [projectriff/system#205]
Several global variables appear to be shared, or at least serially reused, by distinct kubernetes custom resources. This may explain issues, like [this](https://github.com/projectriff/fats/pull/244#issuecomment-558501197), where the `Ready` condition becomes `true` even though the resource isn't really ready. It could also explain other problems where custom resource status behaves unexpectedly.

An example is the global variable [`processorCondSet`](https://github.com/projectriff/system/blob/b1381a44eef732db7a62dd0899d0f3a99af2a77a/pkg/apis/streaming/v1alpha1/processor_lifecycle.go#L36) which is shared between processors, e.g. [here](https://github.com/projectriff/system/blob/b1381a44eef732db7a62dd0899d0f3a99af2a77a/pkg/apis/streaming/v1alpha1/processor_lifecycle.go#L59):
```
func (ps *ProcessorStatus) InitializeConditions() {
	processorCondSet.Manage(ps).InitializeConditions()
}
```

**Comment by scothis** [comment]
@glyn The condition sets are designed to be immutable and reusable. Where is the condition set mutated?

**Comment by glyn** [comment]
Good question. It wasn't clear to me that it was immutable (thanks Go).
