### ISSUE TITLE
Make the service (route) name used by a Knative deployer equal to the deployer name

### ISSUE THREAD

**Issue by jldec** [projectriff/system#216]
For reference, see #200 and #140. This issue addresses the corresponding behavior when using the Knative runtime. The intent is to make the addressable URL of the Knative deployer workload deterministic, so that it can be more easily targeted.

Example with proposed CLI flag (to match the corresponding flag on the core runtime)
`riff knative deployer create inventory --service-name mysvc   ...`

**Comment by scothis** [comment]
Please hold off on starting work. I want to think of them problem holistically

**Comment by glyn** [comment]
We should take a similar approach to https://github.com/projectriff/system/issues/223, but perhaps avoid collisions between knative and core deployer services by appending `-knative` to each knative deployer name to form the service name.

**Comment by glyn** [comment]
> We should take a similar approach to #223, but perhaps avoid collisions between knative and core deployer services by appending `-knative` to each knative deployer name to form the service name.

The consensus in the riff team is to make the knative and core names the same. Now that diagnostics of collisions are better, this should be less of a problem than it was initially (and prompted the approach of using names generated by kubernetes).
