### ISSUE TITLE
Relax stream alias uniqueness

### ISSUE THREAD

**Issue by ericbottard** [projectriff/system#219]
[Current](https://github.com/projectriff/system/blob/15fe8359947dcebb288e52e354b2dfaed247860b/pkg/apis/streaming/v1alpha1/processor_validation.go#L118-L148) stream alias validation is across inputs AND outputs, while it could be made across inputs on one side, and across outputs on the other.

**Comment by fbiville** [comment]
Self-assigning as @AElMehdi is interested in working on this.

**Comment by AElMehdi** [comment]
Thanks @fbiville.

**Comment by AElMehdi** [comment]
> ...while it could be made across inputs on one side, and across outputs on the other.
Do we want to split the validation logic into two separate functions @ericbottard?
Thanks.

**Comment by ericbottard** [comment]
@AElMehdi We don't need to. To clarify, the function that needs to change is `validateStreamAliasUniqueness()` in `processor_validation.go`
