### ISSUE TITLE
Processor controller creates ScaledObject with empty "deploymentName" label value

### ISSUE THREAD

**Issue by glyn** [projectriff/system#240]
It's not clear whether this is intended behaviour or not, but it looks vestigial and it results in a label which isn't particularly useful. Here's the [code](https://github.com/projectriff/system/blob/1377163d1d9832dad87c73e33a9284af1ec3542d/pkg/controllers/streaming/processor_controller.go#L305) that sets the `ScaledObject` label:
```
labels["deploymentName"] = deployment.Name
```
but `deployment.Name` is always the empty string since processor deployments are [created](https://github.com/projectriff/system/blob/1377163d1d9832dad87c73e33a9284af1ec3542d/pkg/controllers/streaming/processor_controller.go#L540) with:
```
GenerateName: fmt.Sprintf("%s-processor-", processor.Name),
```

**Comment by ericbottard** [comment]
Indeed, seems like something we overlooked when we switched to GenerateName
