### ISSUE TITLE
Allow user to specify target port for a core/knative Deployer

### ISSUE THREAD

**Issue by trisberg** [projectriff/system#48]
Currently we force the use of port 8080

**Comment by scothis** [comment]
There's nothing to do here for the Knative runtime, the port config is already exposed via the PodSpec. For the core runtime, we should default the port onto the PodSpec and use that value when creating the probes and fronting service.

**Comment by scothis** [comment]
Not fully resolved for functions until projectriff/streaming-http-adapter/issues/15 is addressed
