### ISSUE TITLE
Change Stream.provider from string to ObjectRef

### ISSUE THREAD

**Issue by ericbottard** [projectriff/system#80]

**Comment by scothis** [comment]
Let's hold off on this one. There are significant complexity and usability concerns introduced by using an ObjectReference, that I don't think are worth the benefit have have different providers with the same name.

1. tools (or users) creating a stream need to know about the specific provisions types API Group and kind (like `streaming.projectriff.io/v1alpha1` and `KafkaProvider`)
2. the controller reconciling the stream needs RBAC permissions, duck types and a rest client to be able to get/watch the provider type

**Comment by ericbottard** [comment]
Closing in favor of https://github.com/projectriff/system/issues/86 to keep loose coupling
